---
# vim:sw=2:ft=ansible
- name: Ensure sentry user exists
  user: name={{sentry_user}}

- name: Ensure sentry directories exists
  file: state=directory path={{sentry_home}} owner={{sentry_user}}

- name: Ensure sentry static dir exists
  file: state=directory path={{sentry_home}}/_static owner={{sentry_user}}

- name: Ensure sentry logfile dir exists
  file: state=directory path={{sentry_logfile_dir}} owner={{sentry_user}} recurse=yes
  when: sentry_logfile_dir != ""

# Try to create virtualenv only if it doesn't exist.
# This way we can re-run the playbook without errors.
- name: Check existince of Sentry virtualenv
  stat: path={{sentry_home}}/env
  register: sentry_has_virtualenv
  sudo: yes
  sudo_user: "{{sentry_user}}"

- name: Create virtualenv for Sentry using chosen Python
  when: sentry_has_virtualenv.stat.exists == False
  shell: virtualenv --python={{sentry_python}} {{sentry_home}}/env
  sudo: yes
  sudo_user: "{{sentry_user}}"

- name: Install Sentry
  pip: name=sentry executable={{sentry_home}}/env/bin/pip version={{sentry_version}}  virtualenv="{{sentry_home}}"/env
  sudo: yes
  sudo_user: "{{sentry_user}}"

- name: Install extensions
  pip: name={{item}} executable={{sentry_home}}/env/bin/pip
  with_items: sentry_extensions

- name: Prepare Sentry
  template: src=sentry.j2 dest={{sentry_home}}/sentry owner={{sentry_user}} mode=0755

- name: Configure Sentry
  template: src=config.py.j2 dest={{sentry_home}}/config.py owner={{sentry_user}}
  register: config
  notify: [sentry restart]

- name: Configure Supervisor
  template: src=supervisor.conf.j2 dest={{supervisor_incdir}}/sentry.conf

- name: Ensure sentry directory owner
  file: state=directory path={{sentry_home}} owner={{sentry_user}} recurse=yes

- name: Upgrade sentry
  shell: "{{sentry_home}}/sentry upgrade --noinput"
  register: sentry_upgrade
  changed_when: sentry_upgrade.rc
  sudo: yes
  sudo_user: "{{sentry_user}}"

- name: Clean Sentry Database
  cron: job="{{sentry_home}}/sentry cleanup --days=30" minute=0 hour=0 user={{sentry_user}}
  when: sentry_cron

- name: Collect sentry static files
  shell: "{{sentry_home}}/sentry django collectstatic --noinput"
  register: sentry_collected
  changed_when: not sentry_collected.stderr.startswith('\n0 static files copied')
  sudo: yes
  sudo_user: "{{sentry_user}}"

- name: Create nginx public key
  copy: content="{{ sentry_nginx_public_key }}" dest="{{ sentry_ssl_certificate }}"
  when: sentry_nginx_public_key is defined and sentry_ssl_certificate

- name: Create nginx private key
  copy: content="{{ sentry_nginx_private_key }}" dest="{{ sentry_ssl_certificate_key }}"
  when: sentry_nginx_private_key is defined and sentry_ssl_certificate_key

- name: Configure Nginx
  template: src=nginx.conf.j2 dest={{nginx_dir|default('/etc/nginx')}}/sites-enabled/sentry.conf
  notify: [nginx reload]
  when: nginx_enabled
